Eatm/Controllers/EatmController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web;
using System.Web.Mvc;
using Eatm.Models;
using Microsoft.Ajax.Utilities;

namespace Eatm.Controllers
{
    public class EatmController : Controller
    {
        private ApplicationDbContext _context;
        public EatmController()
        {
            _context = new ApplicationDbContext();    
        }

        public ActionResult Login()
        {
            if (Session["LoginId"] != null)
            {
                return RedirectToAction("Dashboard");
            }
            return View();
        }

        [HttpPost]
        public ActionResult Login(Account account)
        {
            var customer = _context.Accounts.SingleOrDefault(c =>
                c.CardNumber == account.CardNumber && c.PinNumber == account.PinNumber);

            if (customer == null)
            {
                ViewBag.LoginError = "Invalid Card Number or Pin Number";
                return View("Login");
            }
            Session["LoginId"] = customer.Id;
            return RedirectToAction("Dashboard", new {id = Session["LoginId"] });
        }

        public ActionResult Logout()
        {
            Session.RemoveAll();
            return RedirectToAction("Login");
        }

        public ActionResult Dashboard(int id)
        {
            if (Session["LoginId"] == null)
            {
                return RedirectToAction("Login");
            }
            return View();
        }

        public ActionResult BalanceCheck(int id)
        {
            var loginId = (int)Session["LoginId"];
            if (loginId != id)
            {
                ViewBag.BalanceError = "You are not authorized";
                return View();
            }
            var balance = _context.Accounts.SingleOrDefault(c => c.Id == id);
            return View(balance);
        }

        public ActionResult Withdraw(Transaction transaction, int id)
        {
            var loginId = (int)Session["LoginId"];
            if (loginId != id)
            {
                ViewBag.WithdrawError = "You are not authorized";
                return View();
            }

            var withdraw = _context.Accounts.SingleOrDefault(c => c.Id == loginId);
            var currentDate = DateTime.Today;
            var transactionAccount = _context.Transactions.FirstOrDefault(c => c.AccountId == loginId);
            if (transactionAccount != null)
            {
                var transactionDate = transactionAccount.DateTime.Date;
                var transactionNo = _context.Transactions.Count(c => c.AccountId == loginId && currentDate == transactionDate);
                if (transactionNo <= 3)
                {
                    return View();
                }
                else
                {
                    ViewBag.TransactionLimit = "Daily transaction limit exceed";
                    return RedirectToAction("Dashboard", new { id = Session["LoginId"] });
                }
            }

            return View();
        }

        [HttpPost]
        public ActionResult Withdraw(Account account, Transaction transaction, int id)
        {
            var loginId = (int)Session["LoginId"];
            if (loginId != id)
            {
                ViewBag.WithdrawError = "You are not authorized";
                return View();
            }

            var withdraw = _context.Accounts.SingleOrDefault(c => c.Id == loginId);
            //var currentDate = DateTime.Today;
            //var transactionAccount = _context.Transactions.FirstOrDefault(c => c.AccountId == loginId);
            //var transactionDate = transactionAccount.DateTime.Date;
            //var transactionNo = _context.Transactions.Count(c => c.AccountId == loginId && currentDate == transactionDate);
            var exceedBalance = withdraw.Balance - account.Balance;
            if (withdraw != null)
            {
                if (exceedBalance >= 500)
                {
                    withdraw.Balance -= account.Balance;
                    transaction.AccountId = account.Id;
                    transaction.Amount = account.Balance;
                    transaction.DateTime = DateTime.Now;
                    _context.Transactions.Add(transaction);
                    _context.SaveChanges();
                }
                else
                {
                    ViewBag.LowBalance = "You must keep at least 500 Tk";
                }
            }

            ViewBag.WithdrawBalance = account.Balance + "balance withdraw successfull";
            return RedirectToAction("Dashboard", new { id = Session["LoginId"] });
        }
    }
}

Eatm/Views/Eatm/BalanceCheck.cshtml
@model Eatm.Models.Account
@{
    ViewBag.Title = "BalanceCheck";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@ViewBag.BalanceError
<h2>Balance Check</h2>
 Balance: @Model.Balance

<br />
<li>@Html.ActionLink("Back to Dashboard", "Dashboard", new { id = Session["LoginId"] }, null)</li>

Eatm/Views/Eatm/Dashboard.cshtml
@model Eatm.Models.Account
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Dashboard</h2>
<ul>
    <li>@Html.ActionLink("Balance Check", "BalanceCheck", new { id = Session["LoginId"] }, null)</li>
    <li>@Html.ActionLink("Withdraw Balance", "Withdraw", new { id = Session["LoginId"] }, null)</li>
</ul>

Eatm/Views/Eatm/Login.cshtml
@model Eatm.Models.Account
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login</h2>

<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Login", "Eatm"))
            {
                @Html.AntiForgeryToken()
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(m => m.CardNumber, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.CardNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.CardNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br/>
                <div class="form-group">
                    @Html.LabelFor(m => m.PinNumber, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.PasswordFor(m => m.PinNumber, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.PinNumber, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br/>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Log in" class="btn btn-success" />
                    </div>
                </div>
            }
        </section>
        <p style="color: red">@ViewBag.LogInError</p>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Eatm/Views/Eatm/Withdraw.cshtml
@model Eatm.Models.Account
@{
    ViewBag.Title = "Withdraw";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Withdraw</h2>
@ViewBag.WithdrawError
@ViewBag.LowBalance
@ViewBag.TransactionLimit
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            @using (Html.BeginForm("Withdraw", "Eatm"))
            {
                @Html.AntiForgeryToken()
                <hr />
                <div class="form-group">
                    @Html.LabelFor(m => m.Balance, new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Balance, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Balance, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Withdraw" class="btn btn-success" />
                    </div>
                </div>
            }
        </section>
    </div>
</div>

<li>@Html.ActionLink("Back to Dashboard", "Dashboard", new { id = Session["LoginId"] }, null)</li>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}